# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3f20d1600c530d6090ea993ec7a5c95ea9fbc28175aed269d8e2a546c5c6d4023e5b412ccc4dc299016a89d6e771ca0efa3ead1d04295897198f9eb63a40e0b

test:
  secret_key_base: bc1cc4b595b48de86e64ce851c900d67776dcabef087fa286cc53796e9758bd55ebbe19ddb7e32c37b9ed462b451aa31088e74417468785e37ccb0f323bfc2cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
